
import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class RequestFormCopy extends javax.swing.JFrame {

    /**
     * Creates new form RequestForm
     */
    public RequestFormCopy() {
        initComponents();
        Tables.getInstance().setRequestTable(requestTable);
        
        underline.setVisible(false);
        underlineTitle.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        idNumberField = new javax.swing.JTextField();
        cellNumberField = new javax.swing.JTextField();
        courseComboBox = new javax.swing.JComboBox<>();
        yearLevelComboBox = new javax.swing.JComboBox<>();
        sectionField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        purposeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        approvedByField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dueDateCalendar = new com.toedter.calendar.JDateChooser();
        saveBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        underlineTitle = new javax.swing.JLabel();
        underline = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        comboCheckBox1 = new ComboCheckBox();
        selectBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        borrowedDateCalendar = new com.toedter.calendar.JDateChooser();
        yearLevelPrint = new javax.swing.JTextField();
        coursePrint = new javax.swing.JTextField();
        borrowDatePrint = new javax.swing.JTextField();
        dueDatePrint = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(816, 700));

        container.setBackground(new java.awt.Color(102, 102, 255));
        container.setPreferredSize(new java.awt.Dimension(816, 1056));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 153, 0));
        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setText("Request Form");
        title.setOpaque(true);
        container.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 40));

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        container.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 870, 100, 40));

        nameField.setBackground(new java.awt.Color(255, 255, 204));
        nameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 234, 30));

        idNumberField.setBackground(new java.awt.Color(255, 255, 204));
        idNumberField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(idNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 234, 30));

        cellNumberField.setBackground(new java.awt.Color(255, 255, 204));
        container.add(cellNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 230, 30));

        courseComboBox.setBackground(new java.awt.Color(204, 255, 255));
        courseComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS-Indtech", "BSHM", "BSED", "BEED" }));
        container.add(courseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 130, 30));

        yearLevelComboBox.setBackground(new java.awt.Color(204, 255, 255));
        yearLevelComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yearLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        container.add(yearLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 130, 30));

        sectionField.setBackground(new java.awt.Color(255, 255, 204));
        sectionField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sectionField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(sectionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student Name");
        container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" ID Number");
        container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 94, 16));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cell No.");
        container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Section");
        container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 81, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Purpose");
        container.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 750, 81, 30));

        purposeField.setBackground(new java.awt.Color(255, 255, 204));
        purposeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        purposeField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(purposeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 750, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Approved by");
        container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 790, 94, 30));

        approvedByField.setBackground(new java.awt.Color(255, 255, 204));
        container.add(approvedByField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 790, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Due Date ");
        container.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 790, -1, 30));

        dueDateCalendar.setBackground(new java.awt.Color(255, 255, 204));
        container.add(dueDateCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 790, 160, 30));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        container.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 930, 90, 40));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        container.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 930, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Year level");
        container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Course");
        container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 81, 30));

        underlineTitle.setText("Maintainance");
        container.add(underlineTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 920, -1, -1));

        underline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        underline.setText("_____________________________________________");
        container.add(underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 900, -1, -1));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Condition(Good)", "Condition(Bad)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(1).setMinWidth(100);
            requestTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            requestTable.getColumnModel().getColumn(1).setMaxWidth(100);
            requestTable.getColumnModel().getColumn(2).setMinWidth(100);
            requestTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            requestTable.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        container.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 610, 320));

        comboCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        container.add(comboCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 170, 30));

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        container.add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 70, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Date Borrowed");
        container.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 750, -1, 30));

        borrowedDateCalendar.setBackground(new java.awt.Color(255, 255, 204));
        container.add(borrowedDateCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 160, 30));

        yearLevelPrint.setBackground(new java.awt.Color(255, 255, 204));
        yearLevelPrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yearLevelPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(yearLevelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 130, 30));

        coursePrint.setBackground(new java.awt.Color(255, 255, 204));
        coursePrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coursePrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(coursePrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 130, 30));

        borrowDatePrint.setBackground(new java.awt.Color(255, 255, 204));
        borrowDatePrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        borrowDatePrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(borrowDatePrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 160, 30));

        dueDatePrint.setBackground(new java.awt.Color(255, 255, 204));
        dueDatePrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dueDatePrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.add(dueDatePrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 790, 160, 30));

        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        try {
            Helper.setRequestTableItems();
        } catch (SQLException ex) {
            Logger.getLogger(RequestFormCopy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        Helper helper = new Helper();
        
        String name = nameField.getText();
        String idNumber = idNumberField.getText();
        String cellNumber = cellNumberField.getText();
        String course = (String) courseComboBox.getSelectedItem();
        String yearLevel = (String) yearLevelComboBox.getSelectedItem();
        String section = sectionField.getText();
        
        // table
        
        String purpose = purposeField.getText();
        String approvedBy = approvedByField.getText();
        Date borrowDate = borrowedDateCalendar.getDate();
        Date dueDate = dueDateCalendar.getDate();
        
        // checking
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the name field.");
            return;
        }
        if(idNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the id number field.");
            return;
        }
        if(cellNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the cell number field.");
            return;
        }
        if(section.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the section field.");
            return;
        }
        
        if(!helper.checkRequestValues(requestTable)) {
            return;
        }
        if(purpose.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the purpose field.");
            return;
        }
        if(approvedBy.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the approved by field.");
            return;
        }
        // date
        if (borrowDate != null && dueDate != null) {
            if (borrowDate.after(dueDate)) {
                JOptionPane.showMessageDialog(this, "Borrowed date should before the due date.");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select both borrow and due dates.");
            return;
        }
        
        // SAVE
        // name, idNumber, cellNumber, course, yearLevel, section, purpose, approvedBy, borrowDate, dueDate
        if(helper.saveRequestForm(name, idNumber, cellNumber, course, yearLevel, section, purpose, approvedBy, borrowDate, dueDate, requestTable)) {
            JOptionPane.showMessageDialog(rootPane, "Request submitted successfully.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to submit request. Please try again.");
        }
        
        // RESET
        UserData.getInstance().resetCheckBoxItems();
        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        
        Helper helper = new Helper();

        // VARIABLES
        String name = nameField.getText();
        String idNumber = idNumberField.getText();
        String cellNumber = cellNumberField.getText();
        String course = (String) courseComboBox.getSelectedItem();
        String yearLevel = (String) courseComboBox.getSelectedItem();
        String section = sectionField.getText();
        
        // table
        
        String purpose = purposeField.getText();
        String approvedBy = approvedByField.getText();
        Date borrowDate = borrowedDateCalendar.getDate();
        Date dueDate = dueDateCalendar.getDate();
        
        // checking
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the name field.");
            return;
        }
        if(idNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the id number field.");
            return;
        }
        if(cellNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the cell number field.");
            return;
        }
        if(section.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the section field.");
            return;
        }
        if(!helper.checkRequestValues(requestTable)) {
            return;
        }
        if(purpose.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the purpose field.");
            return;
        }
        if(approvedBy.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in the approved by field.");
            return;
        }
        // date
        if (borrowDate != null && dueDate != null) {
            if (borrowDate.after(dueDate)) {
                JOptionPane.showMessageDialog(this, "Borrowed date should before the due date.");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select both borrow and due dates.");
            return;
        }
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        // set to white
        title.setBackground(new Color(255, 255, 255));
        container.setBackground(new Color(255, 255, 255));
        title.setOpaque(true);
        container.setOpaque(true);
        coursePrint.setText(courseComboBox.getSelectedItem().toString());
        yearLevelPrint.setText(yearLevelComboBox.getSelectedItem().toString());
        courseComboBox.setVisible(false);
        yearLevelComboBox.setVisible(false);
        comboCheckBox1.setVisible(false);
        selectBtn.setVisible(false);
        borrowDatePrint.setText(dateFormat.format(borrowedDateCalendar.getDate()));
        dueDatePrint.setText(dateFormat.format(dueDateCalendar.getDate()));
        borrowedDateCalendar.setVisible(false);
        dueDateCalendar.setVisible(false);
        underline.setVisible(true);
        underlineTitle.setVisible(true);
        saveBtn.setVisible(false);
        exitBtn.setVisible(false);
        printBtn.setVisible(false);
        
        try {
            BufferedImage bi = new BufferedImage(container.getWidth(), container.getHeight(), BufferedImage.TYPE_INT_RGB);
            container.paint(bi.getGraphics());
            
//            String path = "D:\\Downloads\\request-form.jpg";
            String path = "C:\\mabsDownload\\request-form.jpg";
            
            File outputFile = new File(path);
            ImageIO.write(bi, "jpg", outputFile);
            
            // Check if the file exists before attempting to print
            if (outputFile.exists()) {
                Desktop.getDesktop().print(outputFile);
            } else {
                JOptionPane.showMessageDialog(null, "The file doesn't exist: " + path);
            }
            
        } catch (IOException e) {
            e.printStackTrace(); // Print the stack trace for debugging
            JOptionPane.showMessageDialog(rootPane, "Unable to print. Please try again later.");
        }
        
        // set back the styling
        title.setBackground(new Color(255,153,0));
        container.setBackground(new Color(102,102,255));
        coursePrint.setText("");
        yearLevelPrint.setText("");
        courseComboBox.setVisible(true);
        yearLevelComboBox.setVisible(true);
        comboCheckBox1.setVisible(true);
        selectBtn.setVisible(true);
        borrowDatePrint.setText("");
        dueDatePrint.setText("");
        borrowedDateCalendar.setVisible(true);
        dueDateCalendar.setVisible(true);
        underline.setVisible(false);
        underlineTitle.setVisible(false);
        saveBtn.setVisible(true);
        exitBtn.setVisible(true);
        printBtn.setVisible(true);
        
    }//GEN-LAST:event_printBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestFormCopy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField approvedByField;
    private javax.swing.JTextField borrowDatePrint;
    private com.toedter.calendar.JDateChooser borrowedDateCalendar;
    private javax.swing.JTextField cellNumberField;
    private ComboCheckBox comboCheckBox1;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JTextField coursePrint;
    private com.toedter.calendar.JDateChooser dueDateCalendar;
    private javax.swing.JTextField dueDatePrint;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField purposeField;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField sectionField;
    private javax.swing.JButton selectBtn;
    private javax.swing.JLabel title;
    private javax.swing.JLabel underline;
    private javax.swing.JLabel underlineTitle;
    private javax.swing.JComboBox<String> yearLevelComboBox;
    private javax.swing.JTextField yearLevelPrint;
    // End of variables declaration//GEN-END:variables
}
