/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class RequestForm extends javax.swing.JFrame {

    /**
     * Creates new form RequestForm
     */
    public RequestForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        idNumberField = new javax.swing.JTextField();
        cellNoNumber = new javax.swing.JTextField();
        courseComboBox = new javax.swing.JComboBox<>();
        yearLevelComboBox = new javax.swing.JComboBox<>();
        sectionField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        extensionWireCheckBox = new javax.swing.JCheckBox();
        chairsCheckBox = new javax.swing.JCheckBox();
        tablesCheckBox = new javax.swing.JCheckBox();
        othersCheckBox = new javax.swing.JCheckBox();
        othersField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        purposeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        approvedByField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateBorrowedChooser = new com.toedter.calendar.JDateChooser();
        dueDate = new com.toedter.calendar.JDateChooser();
        saveBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(816, 700));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(816, 700));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(816, 1056));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 153, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Request Form");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Print");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 100, 40));

        nameField.setBackground(new java.awt.Color(255, 255, 204));
        nameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 234, 30));

        idNumberField.setBackground(new java.awt.Color(255, 255, 204));
        idNumberField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(idNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 234, 30));

        cellNoNumber.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(cellNoNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 230, 30));

        courseComboBox.setBackground(new java.awt.Color(204, 255, 255));
        courseComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS-Indtech", "BSHM", "BSED", "BEED" }));
        jPanel1.add(courseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 130, 40));

        yearLevelComboBox.setBackground(new java.awt.Color(204, 255, 255));
        yearLevelComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yearLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        jPanel1.add(yearLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 130, 40));

        sectionField.setBackground(new java.awt.Color(255, 255, 204));
        sectionField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sectionField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(sectionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" ID Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 94, 16));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cell No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Section");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 81, -1));

        extensionWireCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        extensionWireCheckBox.setText("Extension Wire");
        jPanel1.add(extensionWireCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        chairsCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chairsCheckBox.setText("Chairs");
        jPanel1.add(chairsCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        tablesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablesCheckBox.setText("Tables");
        jPanel1.add(tablesCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        othersCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        othersCheckBox.setText("Others");
        jPanel1.add(othersCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        othersField.setBackground(new java.awt.Color(255, 255, 204));
        othersField.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(othersField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 270, 30));

        quantityField.setBackground(new java.awt.Color(255, 255, 204));
        quantityField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantityField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Purpose");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 81, -1));

        purposeField.setBackground(new java.awt.Color(255, 255, 204));
        purposeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        purposeField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(purposeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Approved by");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 94, -1));

        approvedByField.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(approvedByField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Date borrowed  ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Due Date ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, -1, -1));

        dateBorrowedChooser.setBackground(new java.awt.Color(255, 255, 204));
        dateBorrowedChooser.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(dateBorrowedChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 160, 30));

        dueDate.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 160, 30));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setText("Save");
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 90, 40));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Year level");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 94, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Course");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 81, -1));

        jLabel4.setText("Maintainance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("_____________________________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField approvedByField;
    private javax.swing.JTextField cellNoNumber;
    private javax.swing.JCheckBox chairsCheckBox;
    private javax.swing.JComboBox<String> courseComboBox;
    private com.toedter.calendar.JDateChooser dateBorrowedChooser;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JButton exitBtn;
    private javax.swing.JCheckBox extensionWireCheckBox;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox othersCheckBox;
    private javax.swing.JTextField othersField;
    private javax.swing.JTextField purposeField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField sectionField;
    private javax.swing.JCheckBox tablesCheckBox;
    private javax.swing.JComboBox<String> yearLevelComboBox;
    // End of variables declaration//GEN-END:variables
}
